version: '3.3'
services: 
  oracle:
    container_name: oracle
    image: toneloc01/oracle-xe-11g:latest
    ports: 
      - '8081:8080'
      - '1521:1521' 
    volumes: 
      - './oracle:/u01/app/oracle'
  jenkins:
    container_name: jenkins
    image: jenkinsci/blueocean:latest
    ports:
      - '8082:8080'
      - '50000:50000'
    volumes: 
      - './jenkins:/var/jenkins_home'
  sonar:
    container_name: sonar
    image: sonarqube:lts
    ports:
      - '9000:9000'
  apache:
    container_name: apache
    image: httpd:latest
    ports:
      - '8083:80'
    volumes:
      - '/home/josemalyson/Documentos/cadastro_versao/VERSAO/cadastro-web/dist:/usr/local/apache2/htdocs/'
